### ISSUE TITLE
application/hal+json is broken 

### ISSUE THREAD

**Issue by mjangid** [temenostech/IRIS#252]
try to get JSON format by setting accept header to application/hal+json you'll get exception 

[hal_json.txt](https://github.com/temenostech/IRIS/files/9960/hal_json.txt)

**Comment by andrewmcguinness** [comment]
One error (not the only one) is that embedded metadata is not handled properly. Line 182 of HALProvider.java passes the type and rawtype of the containing element as the type and rawtype of the embedded element, when in fact they are likely to be different

**Comment by andrewmcguinness** [comment]
The methods "buildfromEntity" and "buildFromOEntity" in https://github.com/temenostech/IRIS/blob/master/interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java simply make no attempt to handle nested properties. That is where it needs to be supported

**Comment by andrewmcguinness** [comment]
JSON output for OEntities merged in PR #291 .  buildFromEntity still needs to be done, readFrom still needs to be done

**Comment by andrewmcguinness** [comment]
Closed by https://github.com/temenostech/IRIS/pull/309
