### ISSUE TITLE
Strange message in logs 'I hope you don't need to build a link from a template for links from this collection, no properties on the collection at the moment'

### ISSUE THREAD

**Issue by aphethean** [temenostech/IRIS#37]
From: Jason Dean 
Sent: 07 December 2012 13:09
To: Aaron Phethean
Subject: Lucas mentioned this is one of yours ;-)

13:08:26,221 INFO  [STDOUT] 13:08:26.221 [http-0.0.0.0-8081-10] WARN  c.t.i.c.h.ResourceStateMachine - I hope you don't need to build a link from a template for links from this collection, no properties on the collection at the moment

**Comment by andrewmcguinness** [comment]
cleaning up--that log message was changed by commit https://github.com/temenostech/IRIS/commit/bf42ca7b53c6194e5b2521ff71df2119d79486fc#diff-aba2c42773786987bb89a6cd52bcb2b3
