### ISSUE TITLE
Clean maven build of IRIS project fails

### ISSUE THREAD

**Issue by alpetric** [temenostech/IRIS#451]
# Maven build of IRIS project fails
I'm trying to just clone and build the entire project locally without any modifications but I'm getting an error.

### Cloning clean repo and cd-ing into it
```
git clone https://github.com/temenostech/IRIS.git
cd IRIS
```

### Using Maven 3 and JDK 1.7
```
$ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

### Error
The following error is thrown when building *com.temenos.interaction:interaction-media-xhtm*

```
[ERROR] Failed to execute goal on project interaction-media-xhtml: Could not resolve dependencies for project com.temenos.interaction:interaction-media-xhtml:jar:0.12.0-SNAPSHOT: 

Failure to find com.googlecode.cambridge:cambridge-core:jar:1.0 in http://repository-temenostech.forge.cloudbees.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of temenos-snapshot-repository has elapsed or updates are forced -> [Help 1]
```

### Reasons?

I read in this support forum that *http://repository-temenostech.forge.cloudbees.com/snapshot* is currently not available. My question is rather: why does it try to download *com.googlecode.cambridge:cambridge-core* from the temenos repo?

**Comment by alpetric** [comment]
OK, I've just re-read the *README* and saw that I have to install com.googlecode.cambridge:cambridge-core but the provided command doesn't work

```
~/git/IRIS$ svn checkout http://cambridge.googlecode.com/svn/trunk/ cambridge-read-only
svn: E160013: Unable to connect to a repository at URL 'http://cambridge.googlecode.com/svn/trunk'
svn: E160013: 'http://cambridge.googlecode.com/svn/trunk' path not found
```

**Comment by aphethean** [comment]
Unfortunately cambridge-core is not in maven central.  I think we need to
remove that dependency.

**Comment by dlgroves** [comment]
I'll do a quick dependency:tree and a code skim to make sure we aren't using this anywhere.

**Comment by aphethean** [comment]
Unfortunately we are using it, but it is pretty trivial template usage for
the xhtml provider I think.  Velocity may be an alternative that is in
maven central, not sure what functionality cambridge brought.

**Comment by kwieconkowski** [comment]
I have removed and replaced Cambridge template engine with Velocity. Now, this particular error during maven compilation should be solved (no dependencies anymore).
