### ISSUE TITLE
useragent-generic-java - Premature end of file error

### ISSUE THREAD

**Issue by mjangid** [temenostech/IRIS#464]
useragent-generic-java throwing following error:
 
**[Fatal Error] :1:1: Premature end of file.
ERROR:  'Premature end of file.'**

Sample Application:
Java class - rename file extension txt to java

[Application.txt](https://github.com/temenostech/IRIS/files/469547/Application.txt)
[Customer.txt](https://github.com/temenostech/IRIS/files/469538/Customer.txt)

**Comment by andrewmcguinness** [comment]
I think this is what I fixed with PR #477 & PR #478 .  The error was being logged but ignored.
@mjangid please reopen if there's a problem with builds later than those.
