### ISSUE TITLE
Temenos APIs not able to handle URL encoding

### ISSUE THREAD

**Issue by phanivenkata** [temenostech/IRIS#490]
The retail APIs are not able to handle URL encoding. This is a problem with most of the libraries or frameworks that send URL encoded requests for security reasons.

For example, the following request URLs _don't_ work for Funds Transfer between accounts:-
/TCMBCommon-iris/TCMBCommon.svc/GB0010001/verFundsTransfer_Tcibs(/'FT161132YYQG/')
/TCMBCommon-iris/TCMBCommon.svc/GB0010001/verFundsTransfer_Tcibs(%27FT161132YYQG%27)

...while the following API call works fine:-
/TCMBCommon-iris/TCMBCommon.svc/GB0010001/verFundsTransfer_Tcibs('FT161132YYQG')

This is a very basic security requirement for any third party looking to call your APIs.

**Comment by mjangid** [comment]
Hi @phanivenkata 
Character / and \ is path component so not allowed as a escape character.

**Comment by cmclopes** [comment]
Hi @phanivenkata 

Can I ask why is this a security issue? Any spec reference?

Imagine this situation:
1. You want to access to this resource `id = ABCD%27EFG`
2. Using the tipical service endpoint defined and registered on wink: `http://server:port/blabla/verTest('{id}')`

The normal way to the user agent access the resource is doing this call:
`http://server:port/blabla/verTest('ABCD%27EFG')`

If the user-agent is encoding the part of the endpoint why is IRIS responsibility to find the correct resource?
`http://server:port/blabla/verTest(%27ABCD%27EFG%27)`

Carlos

**Comment by cmclopes** [comment]
The URL decoding is handled by the PR #361 
Please update to the latest release version.
